### ISSUE TITLE
The sample codes which enable distributedTokenCache is conflict with other docs 

### ISSUE THREAD

**Issue by mywhere** [Azure-Samples/ms-identity-dotnet-advanced-token-cache#12]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
>
In WebAPI's startup.cs file, it enables the DistributedTokenCache with below codes:

```
services.AddMicrosoftIdentityWebApiAuthentication(Configuration)
                .EnableTokenAcquisitionToCallDownstreamApi()
                    .AddMicrosoftGraph(Configuration.GetSection("GraphAPI"))
                .AddIntegratedUserTokenCache();

            services.AddDistributedSqlServerCache(options => {
xxxxx
})
```
But in other Identity samples, it use totally different implementation, like https://github.com/Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2/blob/master/2-WebApp-graph-user/2-2-TokenCache/Startup.cs

```
services.AddAuthentication(OpenIdConnectDefaults.AuthenticationScheme)
                .AddMicrosoftIdentityWebApp(Configuration.GetSection("AzureAd"))
                    .EnableTokenAcquisitionToCallDownstreamApi(initialScopes)
                        .AddMicrosoftGraph(Configuration.GetSection("DownstreamApi"))
                        .AddDistributedTokenCaches();

            services.AddDistributedSqlServerCache(options =>{
xxxxx
})
```

it caused lots of confusing.

### Any log messages given by the failure
>

### Expected/desired behavior
>

### OS and Version?
> Windows 7, 8 or 10. Linux (which distribution). macOS (Yosemite? El Capitan? Sierra?)

### Versions
>

### Mention any other details that might be useful

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by jmprieur** [comment]
@mywhere. Thanks for your feedback. I'm a little bit confused. What is different?
the top one is calling graph. and uses the one line `services.AddMicrosoftIdentityWebApiAuthentication(Configuration)` which is equivalent to the first 2 line of the second one.

I don't understand what's conflicting? can you please elaborate?

**Comment by jmprieur** [comment]
@mywhere ?

**Comment by v-michaelmi** [comment]
Closing issue.

Will reopen if response is made from author.
