### ISSUE TITLE
Cached token expired within a day 

### ISSUE THREAD

**Issue by architect-tarun-narang** [Azure-Samples/ms-identity-dotnet-advanced-token-cache#6]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
>
Incase of token cache between Webapp and Background console application service for the scenario mentioned in https://github.com/Azure-Samples/ms-identity-dotnet-advanced-token-cache/tree/master/1-Integrated-Cache/1-1-WebApp-BgWorker, the application allows to configure the expiration time of the token being cached in the database.
In the webapp application of startup.cs file, I changed the code below to store the token for at least 30 days.

`                //Once expired, the cache entry is automatically deleted by Microsoft.Extensions.Caching.SqlServer library
                options.DefaultSlidingExpiration = TimeSpan.FromDays(30);
`
And in the database too, I used SQL server, it correctly added the expiration time of after a month as shown in the screenshot below:

![image](https://user-images.githubusercontent.com/59596411/116226981-41157380-a771-11eb-9815-9fd8a2a2bec4.png)

However, after a couple of hours, this database entry got changed to 
![image](https://user-images.githubusercontent.com/59596411/116257121-631eee00-a791-11eb-9b62-11027905a089.png)

### Any log messages given by the failure
> No

### Expected/desired behavior
> Now the expiration time of the token was changed to 30 days, it should have cached in the DB for this time but it got expired within sometime. 
Can't the token be cached/stored for 30 days?
### OS and Version?
> Windows 7, 8 or 10. Linux (which distribution). macOS (Yosemite? El Capitan? Sierra?)
Windows 10
### Versions
>

### Mention any other details that might be useful
The background application worked well for a day with the stored token but the next day when the background process executed it failed to retrieve the cached token. Table entries of MSALAccountActivities --> FailedToAcquireToken changed to True from False and Token Cache entry also changed to 1-day expiration from 30 days.
> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by kalyankrishna1** [comment]
to clarify, the token will be updated if by any process, like an app restart , a new token is obtained from AAD. Could you confirm that a call to aAD, resulting in a new Access token didn't happen for us please?

**Comment by architect-tarun-narang** [comment]
I can confirm, neither WebApp was started nor the authentication was done again to get the token.  

In addition to this, when you execute the background process/console application,  the below error comes 

![image](https://user-images.githubusercontent.com/59596411/116722681-57832f80-a9fc-11eb-8620-b9106bd10229.png)
 
As per my understanding, the access token is stored in the database when a person logged in through webapp. Then, the background process picks this access token until it expires from the DB and works fine until the access token expires. And when the access token expires, it should ideally be regenerated using the refresh token but it fails to do so.

**Comment by kalyankrishna1** [comment]
could you (or would you) be able to check if the offline_access scope is being used. The sample needs both the Refresh tokens (granted only of offline_access is sent as a scope) to work correctly

**Comment by architect-tarun-narang** [comment]
documentation did not mention anywhere to pass it but as per your recommendation now, I have passed the scope of offline_access and testing it now. I will share the results asap.

**Comment by architect-tarun-narang** [comment]
@kalyankrishna1 even after passing the scope of "offline_access", the issue remains the same. Are you able to replicate the scenario at your end?

**Comment by architect-tarun-narang** [comment]
Any update on this would be helpful.

**Comment by architect-tarun-narang** [comment]
These are the fresh debug logs, Is the issue reproduced at your end? 

```
Info (False) MSAL 4.17.0.0 MSAL.NetCore Microsoft Windows 10.0.18363 [05/18/2021 07:24:12 - 20cc83ac-50eb-4065-8dc9-3a985c3f9164] MSAL MSAL.NetCore with assembly version '4.17.0.0'. CorrelationId(20cc83ac-50eb-4065-8dc9-3a985c3f9164)
Info (False) MSAL 4.17.0.0 MSAL.NetCore Microsoft Windows 10.0.18363 [05/18/2021 07:24:12 - 20cc83ac-50eb-4065-8dc9-3a985c3f9164] === AcquireTokenSilent Parameters ===
Info (False) MSAL 4.17.0.0 MSAL.NetCore Microsoft Windows 10.0.18363 [05/18/2021 07:24:12 - 20cc83ac-50eb-4065-8dc9-3a985c3f9164] LoginHint provided: False
Info (True) MSAL 4.17.0.0 MSAL.NetCore Microsoft Windows 10.0.18363 [05/18/2021 07:24:12 - 20cc83ac-50eb-4065-8dc9-3a985c3f9164] Account provided: BackgroundWorker.MsalAccount
Info (False) MSAL 4.17.0.0 MSAL.NetCore Microsoft Windows 10.0.18363 [05/18/2021 07:24:12 - 20cc83ac-50eb-4065-8dc9-3a985c3f9164] ForceRefresh: False
Info (True) MSAL 4.17.0.0 MSAL.NetCore Microsoft Windows 10.0.18363 [05/18/2021 07:24:12 - 20cc83ac-50eb-4065-8dc9-3a985c3f9164]
=== Request Data ===
Authority Provided? - True
Client Id - 37b71744-81ba-4762-b071-18da96bf008e
Scopes - Mail.Read User.Read
Redirect Uri - https://replyUrlNotSet
Extra Query Params Keys (space separated) -
ClaimsAndClientCapabilities -
Authority - https://login.microsoftonline.com/4a95f16f-35ba-4a52-9cb3-7f300cdc0c60/
ApiId - AcquireTokenSilent
IsConfidentialClient - True
SendX5C - False
LoginHint -
IsBrokerConfigured - False
HomeAccountId -

Info (True) MSAL 4.17.0.0 MSAL.NetCore Microsoft Windows 10.0.18363 [05/18/2021 07:24:12 - 20cc83ac-50eb-4065-8dc9-3a985c3f9164] === Token Acquisition (SilentRequest) started:
        Authority: https://login.microsoftonline.com/4a95f16f-35ba-4a52-9cb3-7f300cdc0c60/
        Scope: Mail.Read User.Read
        ClientId: 37b71744-81ba-4762-b071-18da96bf008e

Info (False) MSAL 4.17.0.0 MSAL.NetCore Microsoft Windows 10.0.18363 [05/18/2021 07:24:12 - 20cc83ac-50eb-4065-8dc9-3a985c3f9164] Attempting to acquire token using using local cache...
Info (False) MSAL 4.17.0.0 MSAL.NetCore Microsoft Windows 10.0.18363 [05/18/2021 07:24:12 - 20cc83ac-50eb-4065-8dc9-3a985c3f9164] Looking up access token in the cache.
Info (False) MSAL 4.17.0.0 MSAL.NetCore Microsoft Windows 10.0.18363 [05/18/2021 07:24:12 - 20cc83ac-50eb-4065-8dc9-3a985c3f9164] Filtering by tenant id item count before 0 after 0
Info (False) MSAL 4.17.0.0 MSAL.NetCore Microsoft Windows 10.0.18363 [05/18/2021 07:24:12 - 20cc83ac-50eb-4065-8dc9-3a985c3f9164] Filtering by home account id item count before 0 after 0
Info (False) MSAL 4.17.0.0 MSAL.NetCore Microsoft Windows 10.0.18363 [05/18/2021 07:24:12 - 20cc83ac-50eb-4065-8dc9-3a985c3f9164] Filtering by token type item count before 0 after 0
Info (False) MSAL 4.17.0.0 MSAL.NetCore Microsoft Windows 10.0.18363 [05/18/2021 07:24:12 - 20cc83ac-50eb-4065-8dc9-3a985c3f9164] No matching entry found for user or assertion
Verbose (False) MSAL 4.17.0.0 MSAL.NetCore Microsoft Windows 10.0.18363 [05/18/2021 07:24:12 - 20cc83ac-50eb-4065-8dc9-3a985c3f9164] [Instance Discovery] Tried to use network cache provider for login.microsoftonline.com. Success? False
Verbose (False) MSAL 4.17.0.0 MSAL.NetCore Microsoft Windows 10.0.18363 [05/18/2021 07:24:12 - 20cc83ac-50eb-4065-8dc9-3a985c3f9164] [Instance Discovery] Tried to use known metadata provider for login.microsoftonline.com. Success? True
Warning (False) MSAL 4.17.0.0 MSAL.NetCore Microsoft Windows 10.0.18363 [05/18/2021 07:24:12 - 20cc83ac-50eb-4065-8dc9-3a985c3f9164] No app metadata found. Returning unknown
Verbose (False) MSAL 4.17.0.0 MSAL.NetCore Microsoft Windows 10.0.18363 [05/18/2021 07:24:12 - 20cc83ac-50eb-4065-8dc9-3a985c3f9164] [FOCI] App is part of the family or unknown, looking for FRT
Verbose (False) MSAL 4.17.0.0 MSAL.NetCore Microsoft Windows 10.0.18363 [05/18/2021 07:24:12 - 20cc83ac-50eb-4065-8dc9-3a985c3f9164] [Instance Discovery] Tried to use network cache provider for login.microsoftonline.com. Success? False
Verbose (False) MSAL 4.17.0.0 MSAL.NetCore Microsoft Windows 10.0.18363 [05/18/2021 07:24:12 - 20cc83ac-50eb-4065-8dc9-3a985c3f9164] [Instance Discovery] Tried to use known metadata provider for login.microsoftonline.com. Success? True
Info (False) MSAL 4.17.0.0 MSAL.NetCore Microsoft Windows 10.0.18363 [05/18/2021 07:24:13 - 20cc83ac-50eb-4065-8dc9-3a985c3f9164] Refresh token found in the cache? - False
Info (False) MSAL 4.17.0.0 MSAL.NetCore Microsoft Windows 10.0.18363 [05/18/2021 07:24:13 - 20cc83ac-50eb-4065-8dc9-3a985c3f9164] Checking ADAL cache for matching RT
Verbose (False) MSAL 4.17.0.0 MSAL.NetCore Microsoft Windows 10.0.18363 [05/18/2021 07:24:13 - 20cc83ac-50eb-4065-8dc9-3a985c3f9164] [FOCI] FRT found? False
Verbose (False) MSAL 4.17.0.0 MSAL.NetCore Microsoft Windows 10.0.18363 [05/18/2021 07:24:13 - 20cc83ac-50eb-4065-8dc9-3a985c3f9164] [Instance Discovery] Tried to use network cache provider for login.microsoftonline.com. Success? False
Verbose (False) MSAL 4.17.0.0 MSAL.NetCore Microsoft Windows 10.0.18363 [05/18/2021 07:24:13 - 20cc83ac-50eb-4065-8dc9-3a985c3f9164] [Instance Discovery] Tried to use known metadata provider for login.microsoftonline.com. Success? True
Info (False) MSAL 4.17.0.0 MSAL.NetCore Microsoft Windows 10.0.18363 [05/18/2021 07:24:13 - 20cc83ac-50eb-4065-8dc9-3a985c3f9164] Refresh token found in the cache? - False
Info (False) MSAL 4.17.0.0 MSAL.NetCore Microsoft Windows 10.0.18363 [05/18/2021 07:24:13 - 20cc83ac-50eb-4065-8dc9-3a985c3f9164] Checking ADAL cache for matching RT
Verbose (False) MSAL 4.17.0.0 MSAL.NetCore Microsoft Windows 10.0.18363 [05/18/2021 07:24:13 - 20cc83ac-50eb-4065-8dc9-3a985c3f9164] No Refresh Token was found in the cache
Warning (False) MSAL 4.17.0.0 MSAL.NetCore Microsoft Windows 10.0.18363 [05/18/2021 07:24:13 - 20cc83ac-50eb-4065-8dc9-3a985c3f9164] Refreshing the RT failed. Is AAD down? False. Is there an AT in the cache that is usable? False
Warning (False) MSAL 4.17.0.0 MSAL.NetCore Microsoft Windows 10.0.18363 [05/18/2021 07:24:13 - 20cc83ac-50eb-4065-8dc9-3a985c3f9164] Failed to refresh the RT and cannot use existing AT (expired or missing).
Error (True) MSAL 4.17.0.0 MSAL.NetCore Microsoft Windows 10.0.18363 [05/18/2021 07:24:14 - 20cc83ac-50eb-4065-8dc9-3a985c3f9164] MSAL.NetCore.4.17.0.0.MsalUiRequiredException:
        ErrorCode: no_tokens_found
Microsoft.Identity.Client.MsalUiRequiredException: No Refresh Token found in the cache
   at Microsoft.Identity.Client.Internal.Requests.Silent.SilentClientAuthStretegy.FindRefreshTokenOrFailAsync()
   at Microsoft.Identity.Client.Internal.Requests.Silent.SilentClientAuthStretegy.RefreshRtOrFailAsync(CancellationToken cancellationToken)
   at Microsoft.Identity.Client.Internal.Requests.Silent.SilentClientAuthStretegy.ExecuteAsync(CancellationToken cancellationToken)
   at Microsoft.Identity.Client.Internal.Requests.Silent.SilentClientAuthStretegy.ExecuteAsync(CancellationToken cancellationToken)
   at Microsoft.Identity.Client.Internal.Requests.Silent.SilentRequest.ExecuteAsync(CancellationToken cancellationToken)   at Microsoft.Identity.Client.Internal.Requests.Silent.SilentRequest.ExecuteAsync(CancellationToken cancellationToken)   at Microsoft.Identity.Client.Internal.Requests.RequestBase.RunAsync(CancellationToken cancellationToken)
        StatusCode: 0
        ResponseBody:
        Headers:
Could not acquire token for account tarun.narang@softwareconsultingit.onmicrosoft.com.
Error: No Refresh Token found in the cache
  <------------------------>

```

**Comment by jeevanbalanmanoj** [comment]
Hi, I have replicated the scenario by changing to TimeSpan.FromDays(30); and I am not able to reproduce the issue. It's working as expected and no change in expiration time after 2 hours in sql db is observed. Can you please let us know if you have followed the sample exactly as is or if you have made some other customizations as well? @architect-tarun-narang

**Comment by architect-tarun-narang** [comment]
It worked fine for me until two hours or so, till the time access token is not expired. However, in my case after 8-10 hours, I started facing this issue for which I shared the debug logs as well. Request you to please give it a try after 10 hours.

In addition to this, do the logs provided above confirms any issue? Thanks

**Comment by jeevanbalanmanoj** [comment]
I just tried after almost 24 hours and it still works. Can you please confirm if you have used the sample as is? Did you use the [automated scripts](https://github.com/Azure-Samples/ms-identity-dotnet-advanced-token-cache/blob/master/1-Integrated-Cache/1-1-WebApp-BgWorker/README.md#step-2-register-the-web-app-project-with-your-azure-ad-tenant) to create the app reg and configurations? If not can you please do it that way and see if working fine?

**Comment by architect-tarun-narang** [comment]
I did not use the automated script to create the app and give it a try as per your suggestions. 

Yes, we used the same sample program, even this issue was raised with the Microsoft team and they were able to reproduce this problem at their end. 

By looking at the logs above, do you see any problem, why the refresh token was not found in the cache? In the meanwhile, I will try this with an automated script. Thanks

**Comment by jeevanbalanmanoj** [comment]
@architect-tarun-narang Please let us know which Microsoft team was able to reproduce this issue. Can you please loop me in on the thread?

**Comment by architect-tarun-narang** [comment]
Sure, I will drop an email to the Microsoft team requesting them to loop you in. I don't have your email address but I have requested Nadim Akhtar (from Microsoft) to loop you in.

**Comment by jeevanbalanmanoj** [comment]
@architect-tarun-narang did you try running the sample with the automated scripts? Is it still failing?

**Comment by jeevanbalanmanoj** [comment]
@architect-tarun-narang  Hi, after more than 24 hours the issue has now happened in my setup. Thank you for your patience with this. We are looking into this on priority

**Comment by jeevanbalanmanoj** [comment]
@architect-tarun-narang can you please add the following line to the background worker's [program.cs file (line 34) ](https://github.com/Azure-Samples/ms-identity-dotnet-advanced-token-cache/blob/aed6f2df4563e6f0335cd84b09479a8b8195401c/1-Integrated-Cache/1-1-WebApp-BgWorker/BackgroundWorker/Program.cs#L34) also?                       
`options.DefaultSlidingExpiration = TimeSpan.FromDays(30);
 `
 Basically the issue happened because you updated the time from 2 hours to 30 days only in the webapp and background worker used the default value of 20 mins for the [DefaultSlidingExpiration property](https://docs.microsoft.com/en-us/dotnet/api/microsoft.extensions.caching.sqlserver.sqlservercacheoptions.defaultslidingexpiration?view=dotnet-plat-ext-3.1#Microsoft_Extensions_Caching_SqlServer_SqlServerCacheOptions_DefaultSlidingExpiration) hence the refresh token became shortlived and then removed from the db post 20 mins leading to the refresh token not found error. 
 
 Do try this and let us know if your issue is resolved

**Comment by jeevanbalanmanoj** [comment]
@architect-tarun-narang  did it help?

**Comment by architect-tarun-narang** [comment]
Thanks @jeevanbalanmanoj , it worked, the issue is resolved now.

**Comment by kalyankrishna1** [comment]
Fix deployed
