### ISSUE TITLE
Does it handle the access token expiration scenario?

### ISSUE THREAD

**Issue by felixt-c** [Azure-Samples/ms-identity-dotnet-advanced-token-cache#7]
for instance, a background long running job keep getting data from blob with delegated user https://storage.azure.com/user_impersonation scope and able to refresh token even after the token expires.

In that case do we need offline_access scope so that refresh token is also cached?

**Comment by kalyankrishna1** [comment]
The sample actually caches both the refresh tokes and access tokens. Refresh tokens are the ones that need caching to enable refreshing access tokens at a regular intervals. So yes, the offline_access scope is required
