### ISSUE TITLE
This sample app referenced some preview versions SDK

### ISSUE THREAD

**Issue by mywhere** [Azure-Samples/ms-identity-dotnet-advanced-token-cache#9]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [x] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
> the sample app is still using Microsoft.Identity.Web with Version 0.2.1-preview, which doesn't provide much useful information. Can anyone update the sample app with latest version (currently it's Version https://www.nuget.org/packages/Microsoft.Identity.Web/1.14.0)

### Any log messages given by the failure
>

### Expected/desired behavior
>

### OS and Version?
> Windows 7, 8 or 10. Linux (which distribution). macOS (Yosemite? El Capitan? Sierra?)

### Versions
>

### Mention any other details that might be useful

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by derisen** [comment]
@mywhere good catch! We'll make sure to update the dependencies

**Comment by kalyankrishna1** [comment]
updated
